export default {
  common: {
    cancel: 'Cancel',
    language: 'Language',
    change_language: 'Change Language to',
    noProviders: 'No providers found',
    poweredBy: 'Powered by SSQUARE LOGIC',
    continue: 'Continue',
    front: 'Front',
    back: 'Back',
    notAvailable: 'Not available',
  },

  settings: {
    title: 'Settings',
    privacy_policy: 'Privacy Policy',
    terms_conditions: 'Terms & Conditions',
    support: 'Support',
    logout: 'Logout',
    delete_account: 'Delete Account',
    confirm_logout: 'Are you sure you want to logout?',
    confirm_delete: 'This action cannot be undone!',
    support_success_title: 'Ticket Submitted',
    support_success_subtitle:
      'Your support request has been submitted successfully. Our team will contact you soon.',
    ok: 'OK',
    support_ticket_title: 'Support Ticket',
    ticket_type: 'Ticket Type',
    select_ticket_type: 'Select ticket type',
    summary: 'Summary',
    enter_summary: 'Enter short summary',
    description: 'Description',
    describe_issue: 'Describe your issue',
    submit: 'Submit',

    ticket_types: {
      payment: 'Payment Issue',
      bug: 'App Bug',
      provider: 'Provider Complaint',
      general: 'General Query',
    },
    delete_title: 'Delete Account',
    delete_subtitle:
      'Enter your phone number to confirm account deletion. This action cannot be undone.',
    enter_phone: 'Enter phone number',
    delete: 'Delete',
  },

  tabs: {
    dashboard: 'Home',
    notifications: 'Notifications',
    profile: 'Profile',
    settings: 'Settings',
  },
  home: {
    greeting: 'Hello 👋',
    title: 'Find Best Services',
    searchPlaceholder: 'Search services...',
    categories: 'Categories',
    topRated: 'Top Rated',
  },

  profile: {
    title: 'Profile Required',
    blockSubtitle: 'Complete your profile & payment to unlock access',
    later: 'Later',
    completeNow: 'Complete Now',
    profilePaggeTitle: 'Profile Details',
    edit: 'Edit',
    name: 'Full Name',
    address: 'Address',
    city: 'City',
    state: 'State',
    pincode: 'Pincode',
    uploadId: 'Upload ID Proof',
    continue: 'Continue',
    updateSuccessTitle: 'Profile Updated',
    updateSuccessSubtitle: 'Your profile has been updated successfully',
    ok: 'OK',

    personalInfo: 'Personal Info',
    addressDetails: 'Address Details',
    professionalDetails: 'Professional Details',
    mobileNumber: 'Mobile Number',
    village: 'Village',
    tehsil: 'Tehsil',
    category: 'Service Category (e.g. Electrician)',
    experience: 'Experience (years)',
    aboutService: 'About your service',
  },
  categories: {
    electrician: 'Electrician',
    plumber: 'Plumber',
    salon: 'Salon',
    ac_repair: 'AC Repair',
    carpenter: 'Carpenter',
    painter: 'Painter',
    cleaning: 'Cleaning',
    pest_control: 'Pest Control',
    appliance_repair: 'Appliance Repair',
    beauty_makeup: 'Beauty & Makeup',
  },
  splash: {
    appName: 'Service Finder',
    tagline: 'Find trusted local professionals',
  },
  login: {
    mobilePlaceholder: 'Enter mobile number',
    sendOtp: 'Send OTP',
  },
  otp: {
    enterOtp: 'Enter OTP',
    verifyOtp: 'Verify OTP',
    resendOtp: 'Resend OTP',
  },
  roleSelection: {
    findServicesTitle: 'Find Services',
    findServicesDesc: 'Browse and hire trusted professionals',
    provideServicesTitle: 'Provide Services',
    provideServicesDesc: 'Offer your services and grow your business',
    bothTitle: 'Both',
    bothDesc: 'Use the app as customer and provider',
  },
  cameraModal: {
    title: 'Select Image',
    camera: 'Open Camera',
    gallery: 'Choose from Gallery',
  },
  providerDetails: {
    location: 'Location',
    distance: 'Distance',
    experience: 'Experience',
    servicesDone: 'Services Done',
    rating: 'Rating',
    about: 'About',
    aboutDesc1: 'is a professional',
    aboutDesc2: 'with over',
    yearsExperience: 'years of experience and completed',
    servicesCompleted: 'services successfully.',
    call: 'Call',
    whatsapp: 'WhatsApp',
  },
  payment: {
    title: 'Payment',
    subtitle: 'Choose a payment method to continue',
    totalAmount: 'Total Amount',
    upi: 'Pay via UPI',
    card: 'Credit / Debit Card',
    cod: 'Pay Later (Approval)',
    pay: 'Pay',
    blockSubtitle: 'Please complete payment to access providers',

  },
  errors: {
    enterMobile: "Please enter mobile number",
    invalidMobile: "Please enter valid 10 digit mobile number",
    otpFailed: "Failed to send OTP",
    invalidOtp: "Invalid OTP. Please try again",
    network: "Network error, please try again",
    sessionExpired: "Session expired. Please login again.",
    timeout: "Request timeout. Please try again.",
    noInternet: "No internet connection.",
    connectionIssue: 'Unable to connect. Please check your internet connection.',
    somethingWrong: 'Something went wrong.',
  }
};