export default {
  common: {
    cancel: 'रद्द करें',
    language: 'भाषा',
    change_language: 'भाषा बदलें',
    noProviders: 'कोई सेवा प्रदाता नहीं मिला',
    poweredBy: 'Powered by SSQURE LOGIC',
    continue: 'जारी रखें',
    front: 'फ्रंट',
    back: 'बैक',
  },

  settings: {
    title: 'सेटिंग्स',
    privacy_policy: 'गोपनीयता नीति',
    terms_conditions: 'नियम और शर्तें',
    support: 'सपोर्ट',
    logout: 'लॉगआउट',
    delete_account: 'अकाउंट डिलीट करें',
    confirm_logout: 'क्या आप वाकई लॉगआउट करना चाहते हैं?',
    confirm_delete: 'यह क्रिया वापस नहीं हो सकती!',
    support_success_title: 'टिकट सबमिट हो गई',
    support_success_subtitle:
      'आपका सपोर्ट अनुरोध सफलतापूर्वक सबमिट हो गया है। हमारी टीम जल्द आपसे संपर्क करेगी।',
    ok: 'ठीक है',
    support_ticket_title: 'सपोर्ट टिकट',
    ticket_type: 'टिकट प्रकार',
    select_ticket_type: 'टिकट प्रकार चुनें',
    summary: 'सारांश',
    enter_summary: 'संक्षिप्त विवरण लिखें',
    description: 'विवरण',
    describe_issue: 'अपनी समस्या बताएं',
    submit: 'सबमिट करें',

    ticket_types: {
      payment: 'पेमेंट समस्या',
      bug: 'ऐप बग',
      provider: 'प्रोवाइडर शिकायत',
      general: 'सामान्य प्रश्न',
    },
    delete_title: 'खाता हटाएं',
    delete_subtitle:
      'खाता हटाने की पुष्टि के लिए अपना मोबाइल नंबर दर्ज करें। यह कार्रवाई वापस नहीं ली जा सकती।',
    enter_phone: 'मोबाइल नंबर दर्ज करें',
    delete: 'हटाएं',
  },

  tabs: {
    dashboard: 'होम',
    notifications: 'सूचनाएं',
    profile: 'प्रोफाइल',
    settings: 'सेटिंग्स',
  },
  home: {
    greeting: 'नमस्ते 👋',
    title: 'सर्वश्रेष्ठ सेवाएं खोजें',
    searchPlaceholder: 'सेवाएं खोजें...',
    categories: 'श्रेणियां',
    topRated: 'टॉप रेटेड',
  },

  profile: {
    title: 'प्रोफाइल आवश्यक',
    blockSubtitle: 'एक्सेस के लिए प्रोफाइल और पेमेंट पूरा करें',
    later: 'बाद में',
    completeNow: 'अभी पूरा करें',
    profilePaggeTitle: 'प्रोफाइल विवरण',
    edit: 'संपादित करें',
    name: 'पूरा नाम',
    address: 'पता',
    city: 'शहर',
    state: 'राज्य',
    pincode: 'पिनकोड',
    uploadId: 'आईडी प्रूफ अपलोड करें',
    continue: 'जारी रखें',
    updateSuccessTitle: 'प्रोफाइल अपडेट हो गया',
    updateSuccessSubtitle: 'आपकी प्रोफाइल सफलतापूर्वक अपडेट हो गई है',
    ok: 'ठीक है',

    personalInfo: 'व्यक्तिगत जानकारी',
    addressDetails: 'पता संबंधी जानकारी',
    professionalDetails: 'पेशेवर जानकारी',
    mobileNumber: 'मोबाइल नंबर',
    village: 'गाँव',
    tehsil: 'तहसील',
    category: 'सेवा श्रेणी (जैसे: इलेक्ट्रीशियन)',
    experience: 'अनुभव (सालों में)',
    aboutService: 'अपनी सेवा के बारे में लिखें',
  },
  categories: {
    electrician: 'इलेक्ट्रीशियन',
    plumber: 'प्लम्बर',
    salon: 'सैलून',
    ac_repair: 'एसी रिपेयर',
    carpenter: 'कारपेंटर',
    painter: 'पेंटर',
    cleaning: 'क्लीनिंग',
    pest_control: 'पेस्ट कंट्रोल',
    appliance_repair: 'एप्लायंस रिपेयर',
    beauty_makeup: 'ब्यूटी और मेकअप',
  },
  splash: {
    appName: 'सर्विस फाइंडर',
    tagline: 'विश्वसनीय स्थानीय सेवाएं खोजें',
  },
  login: {
    mobilePlaceholder: 'मोबाइल नंबर दर्ज करें',
    sendOtp: 'ओटीपी भेजें',
  },
  otp: {
    enterOtp: 'ओटीपी दर्ज करें',
    verifyOtp: 'ओटीपी सत्यापित करें',
    resendOtp: 'ओटीपी पुनः भेजें',
  },
  roleSelection: {
    findServicesTitle: 'सेवाएं खोजें',
    findServicesDesc: 'विश्वसनीय प्रोफेशनल्स को ब्राउज़ करें और हायर करें',
    provideServicesTitle: 'सेवाएं प्रदान करें',
    provideServicesDesc: 'अपनी सेवाएं दें और अपना व्यवसाय बढ़ाएं',
    bothTitle: 'दोनों',
    bothDesc: 'ग्राहक और प्रोवाइडर दोनों के रूप में ऐप का उपयोग करें',
  },
  cameraModal: {
    title: 'इमेज चुनें',
    camera: 'कैमरा खोलें',
    gallery: 'गैलरी से चुनें',
  },
  providerDetails: {
    location: 'स्थान',
    distance: 'दूरी',
    experience: 'अनुभव',
    servicesDone: 'सेवाएं पूरी',
    rating: 'रेटिंग',
    about: 'परिचय',
    aboutDesc1: 'एक प्रोफेशनल',
    aboutDesc2: 'हैं जिनके पास',
    yearsExperience: 'साल का अनुभव है और',
    servicesCompleted: 'सेवाएं सफलतापूर्वक पूरी की हैं।',
    call: 'कॉल',
    whatsapp: 'व्हाट्सऐप',
  },
  payment: {
    title: 'भुगतान',
    subtitle: 'जारी रखने के लिए भुगतान का तरीका चुनें',
    totalAmount: 'कुल राशि',
    upi: 'UPI से भुगतान करें',
    card: 'क्रेडिट / डेबिट कार्ड',
    cod: 'बाद में भुगतान (स्वीकृति)',
    pay: 'भुगतान करें',
    blockSubtitle: 'प्रोवाइडर एक्सेस करने के लिए कृपया पेमेंट पूरा करें'
  },
  errors: {
    enterMobile: "कृपया मोबाइल नंबर दर्ज करें",
    invalidMobil: "कृपया सही 10 अंकों का मोबाइल नंबर दर्ज करें",
    otpFailed: "OTP भेजने में विफल",
    invalidOtp: "गलत OTP, कृपया दोबारा प्रयास करें",
    network: "नेटवर्क एरर, कृपया पुनः प्रयास करें",
    sessionExpired: "सत्र समाप्त हो गया है। कृपया दोबारा लॉगिन करें।",
    timeout: "अनुरोध में समय अधिक लग रहा है। कृपया पुनः प्रयास करें।",
    noInternet: "इंटरनेट कनेक्शन उपलब्ध नहीं है।",
  }
};